spring:
  # this is used for frontend debugging (doesn't cache html templates)
  thymeleaf:
    cache: false

  # ===============================
  # DATABASE - H2
  # ===============================

  h2:
    console:
      enabled: true

  datasource:
    schema: classpath:/db/h2/schema.sql

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate