spring:

  # ===============================
  # DATABASE
  # ===============================
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/todo
    username: todo
    password: ToDo2018

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    generate-ddl: true
    show-sql: true