spring:

  # ===============================
  # DATABASE
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: todo
    password: ToDo2018
    schema: classpath:/db/postgres/schema.sql

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true

server:
  ssl:
    key-store: /etc/letsencrypt/live/yourdomain.com/keystore.p12
    key-store-password: ToDo@)!(
    keyStoreType: PKCS12
    key-alias: tomcat