spring:

  # ===============================
  # DATABASE
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: todo
    password: ToDo2018
    schema: classpath:/db/postgres/schema.sql

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true