spring:
  # this is used for frontend debugging (doesn't cache html templates)
  thymeleaf:
    cache: false

  # ===============================
  # DATABASE - H2
  # ===============================

  h2:
    console:
      enabled: true

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true